name: ct-eus-vessel
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - scipy
  - scikit-image
  - simpleitk
  - pydicom
  - pyyaml
  - pandas
  - pytest
  - pip
  - pip:
      - totalsegmentator
